// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Person.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//定义一个protobuf 协议
type Person struct {
	Name   string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age    int32          `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Emails []string       `protobuf:"bytes,3,rep,name=emails,proto3" json:"emails,omitempty"`
	Phones []*PhoneNumber `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*Person_School
	//	*Person_Sovre
	Data                 isPerson_Data `protobuf_oneof:"Data"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_841ab6396175eaf3, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *Person) GetPhones() []*PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type isPerson_Data interface {
	isPerson_Data()
}

type Person_School struct {
	School string `protobuf:"bytes,5,opt,name=school,proto3,oneof"`
}

type Person_Sovre struct {
	Sovre uint32 `protobuf:"varint,6,opt,name=sovre,proto3,oneof"`
}

func (*Person_School) isPerson_Data() {}

func (*Person_Sovre) isPerson_Data() {}

func (m *Person) GetData() isPerson_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Person) GetSchool() string {
	if x, ok := m.GetData().(*Person_School); ok {
		return x.School
	}
	return ""
}

func (m *Person) GetSovre() uint32 {
	if x, ok := m.GetData().(*Person_Sovre); ok {
		return x.Sovre
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Person) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Person_OneofMarshaler, _Person_OneofUnmarshaler, _Person_OneofSizer, []interface{}{
		(*Person_School)(nil),
		(*Person_Sovre)(nil),
	}
}

func _Person_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Person)
	// Data
	switch x := m.Data.(type) {
	case *Person_School:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.School)
	case *Person_Sovre:
		b.EncodeVarint(6<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Sovre))
	case nil:
	default:
		return fmt.Errorf("Person.Data has unexpected type %T", x)
	}
	return nil
}

func _Person_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Person)
	switch tag {
	case 5: // Data.school
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Data = &Person_School{x}
		return true, err
	case 6: // Data.sovre
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Data = &Person_Sovre{uint32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Person_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Person)
	// Data
	switch x := m.Data.(type) {
	case *Person_School:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.School)))
		n += len(x.School)
	case *Person_Sovre:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Sovre))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

//一个protobuf 协议的消息
type PhoneNumber struct {
	Number               string   `protobuf:"bytes,1,opt,name=Number,proto3" json:"Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_841ab6396175eaf3, []int{1}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "pb.Person")
	proto.RegisterType((*PhoneNumber)(nil), "pb.PhoneNumber")
}

func init() { proto.RegisterFile("Person.proto", fileDescriptor_841ab6396175eaf3) }

var fileDescriptor_841ab6396175eaf3 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x6a, 0x84, 0x30,
	0x10, 0x86, 0x8d, 0xd1, 0x80, 0x63, 0x4b, 0xcb, 0x1c, 0x24, 0xc7, 0x20, 0x94, 0xe6, 0xe4, 0xa1,
	0x7d, 0x83, 0xd2, 0x83, 0xa7, 0x22, 0x79, 0x83, 0xa4, 0x84, 0x5a, 0x50, 0x13, 0x12, 0x77, 0xdf,
	0x69, 0xdf, 0x72, 0x89, 0xe6, 0xb0, 0xb7, 0xef, 0xfb, 0x07, 0x66, 0xfe, 0x81, 0xa7, 0xc9, 0x86,
	0xe8, 0xb6, 0xc1, 0x07, 0xb7, 0x3b, 0x2c, 0xbd, 0xe9, 0x6f, 0x04, 0xd8, 0x19, 0x22, 0x42, 0xb5,
	0xe9, 0xd5, 0x72, 0x22, 0x88, 0x6c, 0xd4, 0xc1, 0xf8, 0x0a, 0x54, 0xff, 0x59, 0x5e, 0x0a, 0x22,
	0x6b, 0x95, 0x10, 0x3b, 0x60, 0x76, 0xd5, 0xff, 0x4b, 0xe4, 0x54, 0x50, 0xd9, 0xa8, 0x6c, 0xf8,
	0x0e, 0xcc, 0xcf, 0x6e, 0xb3, 0x91, 0x57, 0x82, 0xca, 0xf6, 0xe3, 0x65, 0xf0, 0x66, 0x98, 0x52,
	0xf2, 0x73, 0x59, 0x8d, 0x0d, 0x2a, 0x8f, 0x91, 0x03, 0x8b, 0xbf, 0xb3, 0x73, 0x0b, 0xaf, 0xd3,
	0xa1, 0xb1, 0x50, 0xd9, 0xb1, 0x83, 0x3a, 0xba, 0x6b, 0xb0, 0x9c, 0x09, 0x22, 0x9f, 0xc7, 0x42,
	0x9d, 0xfa, 0xc5, 0xa0, 0xfa, 0xd6, 0xbb, 0xee, 0xdf, 0xa0, 0x7d, 0x58, 0x98, 0x9a, 0x9c, 0x94,
	0x1b, 0x67, 0x33, 0xec, 0xf8, 0xee, 0xf3, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x0d, 0x3f, 0xea,
	0xed, 0x00, 0x00, 0x00,
}
